### ISSUE TITLE
Don't work!!!

### ISSUE THREAD

**Issue by thearabbit** [nchutchind/vue-outside-events#1]
my code
```
<div v-click-outside="onClickOutside">
       <el-button type="danger" @click="remove">Del</el-button>
</div>
------
onClickOutside (event) {
     console.log('outside');
}
```
When I click button , `onClickOutside` method work too.
Should be don't work because button is it `onClickOutside`

**Comment by nchutchind** [comment]
I'm not certain I understand.

I just modified the demo-click-outside.html page from the docs folder so that all of the letters displayed were now buttons. Behavior was identical to before.

The script is basically adding a listener to the document that listens for an event (in this case, a click). It checks to see if the event target was the element we added the listener to or was inside the element we added the listener to.

**Comment by nchutchind** [comment]
I'd be happy to look at a jsfiddle or other code example if you have one.

**Comment by thearabbit** [comment]
Thanks for your reply.
I tried in [jsfiddle](https://jsfiddle.net/theara/4gj422r4/), but don't work for import.

**Comment by nchutchind** [comment]
I looked at your jsFiddle. It looks like GitHub sends the javascript file back as HTML, so jsFiddle won't execute it.
I changed the URL for the directive js to the file on GitHub Pages (it's the same file, but the server sends it back as Javascript instead as HTML).

You can see it here: [jsFiddle](https://jsfiddle.net/4gj422r4/6/)

Again the only thing I changed was where the file was getting pulled from. You could technically achieve the same thing by putting the script directly in your page, [like this](https://jsfiddle.net/4gj422r4/7/)

**Comment by thearabbit** [comment]
Thanks for your helping, I your `jsFiddle` work fine.
Now will try on my project again.

**Comment by thearabbit** [comment]
OK, now work fine.
👍 👍 👍
