### ISSUE TITLE
Event undefined in handler function?

### ISSUE THREAD

**Issue by janzheng** [nchutchind/vue-outside-events#6]
Hi there, thanks for this plugin. Super useful. I'm a complete Vue noob so please bear with me:

I'm getting `Uncaught TypeError: Cannot read property 'target' of undefined` when importing into a webpack project, as the event seems to not be defined in the handler function. I don't have any problems with your examples where you just include the JS file. 

The events are all triggering properly, but I can't access the event information at all, either through the jQuery or the regular event handlers. 

Do you have any tips? Thanks!
J

**Comment by janzheng** [comment]
It's returning the event properly when I'm emitting a trigger:
~~~
    $(document).trigger({
      type: "onFoo",
      name: "banana",
      isBanana: true
    });
~~~
and I'm setting the jQuery event like so: `v-event-outside.jquery="{ name: 'onFoo', handler: onOutside, foo: 'vueData' }"` 

In case anyone else get trippped up

**Comment by nchutchind** [comment]
I'm sorry I never responded. Github didn't let me know that there was anything here. 

Don't worry about being a Vue noob. I keep wanting to rewrite vue code from 6 months ago (ongoing) because I understand it better now. It's a learning process. :)

I'm currently using this library with webpack and including it with a require() statement, so I know that much works. I'm not sure exactly what the problem you're describing is, but it sounds like you're trying to pass extra data along with an outside event. The demo "[Binding Data to the Handler](https://nchutchind.github.io/vue-outside-events/docs/demo-pass-object.html)" should be what you're looking for. Essentially, if looks like you figured that much out. The click handler usually takes parameters for the event and the element, but when you add extra data like this, a third parameters will include the extras.

`v-click-outside="{ handler: onClickOutside, isImportant: true }"`

    onClickOutside( e, elem, extras ) {
        console.log( "Event", e );
        console.log( "Element", elem );
        console.log( "Is important?", extras.isImportant );
    }

Just remember that the handler will fire for every single element you've attached it to, so you may want to check which element is firing to see if you care about the extra data.
